from __future__ import annotations

WINDOW_DEFAULT = (1180, 760)
WINDOW_MINIMUM = (960, 640)

MENU_PANEL_WIDTH = 500
SETUP_PANEL_WIDTH = 560
LOBBY_PANEL_WIDTH = 660
TEXT_PANEL_WIDTH = 760

CONTROL_HEIGHT = 52
PRIMARY_HEIGHT = 60
PANEL_RADIUS = 28
INPUT_RADIUS = 15

PAGE_MARGIN_COMPACT = 24
PAGE_MARGIN_DEFAULT = 40
PAGE_MARGIN_LARGE = 64


def page_margin(width: int) -> int:
    if width < 1100:
        return PAGE_MARGIN_COMPACT
    if width < 1400:
        return PAGE_MARGIN_DEFAULT
    return PAGE_MARGIN_LARGE
